version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: