@startuml anonchat - sequence

actor Пользователь as u
participant Сайт as f
participant СокетСервер as s

==Инициализация==

u -> f: Зашёл на сайт
f -> s: Запрос на сокет
s -> s: Инициализация сокета
s --> f: Передача данных о созданном сокете
f --> u: Сайт прогрузился

==Поиск собеседника==

u -> f: Заполнил и отправил форму \nдля поиска анонимного \nсобеседника
f -> s: Передача данных с формы
f --> u: Пользователь находится \nв странице поиска
s -> s: Создаёт комнату \nили находит комнату \nсобеседника
s --> f: Собеседник найден
f --> u: Пользователь переходит\nв страницу чата с собеседником

@enduml