@startuml anonchat - sequence

actor Собеседник1 as u1
participant Сайт  as f1
participant СокетСервер as s
participant Сайт  as f2
actor Собеседник2 as u2

==Общение с собеседником==

u1 -> f1  : Печатает
f1 -> s   : Пользователь печатает
s  -> f2  : Собеседник печатает
f2 -> u2  : Появляется надпись \n"Собеседник печатает"
u1 -> f1  : Отправляет сообщение
f1 --> u1 : Появляется в чате\nотправленное сообщение
f1 -> s   : Передаётся сообщение
s  -> f2  : Передаётся сообщение
f2 -> u2  : Полученное сообщение\nпоявляется в чате

==Завершение общения через выход из сайта==

u1 -> f1  : Пользователь выход из сайта
f1 -> s   : Сокет отключается
s  -> s   : Все участники общения\nвыходят из комнаты, а\nкомната удаляется
s  -> f2  : Собеседник отключился
f2 -> u2  : Перенаправляет пользователя\nна главную страницу сайта

==Завершение общения через кнопку==

u1 -> f1  : Пользователь нажимает \nкнопку "Завершить"
f1 --> u1 : Перенаправляет пользователя\nна главную страницу сайта
f1 -> s   : Передаётся данные\nо том, что пользователь\nвышел из комнаты
s  -> s   : Все участники общения\nвыходят из комнаты, а\nкомната удаляется
s  -> f2  : Собеседник отключился
f2 -> u2  : Перенаправляет пользователя\nна главную страницу сайта

@enduml